require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Exponea' do

  # React Native and its dependencies

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod "ExponeaSDK", "2.12.3"
  pod 'AnyCodable-FlightSchool', '0.4.0'
end

target 'Tests' do
  pod 'Quick'
  pod 'Nimble', '8.0.7'
end

# Set deployment target for all pods to get rid of (most of) warnings
post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end

    # We need to make one crude patch to RCT-Folly - set `__IPHONE_10_0` to our iOS target + 1
    # https://github.com/facebook/flipper/issues/834 - 84 comments and still going...
   `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_12_0/' Pods/RCT-Folly/folly/portability/Time.h`
end
