# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'

target 'Exponea' do

  # React Native and its dependencies

  config = use_native_modules!

  use_react_native!(
      :path => config[:reactNativePath],
      # to enable hermes on iOS, change `false` to `true` and then install pods
      :hermes_enabled => false
    )

  pod "ExponeaSDK", "3.8.2"
  pod 'AnyCodable-FlightSchool', '0.4.0'
end

target 'Tests' do
  pod 'Quick', '5.0.1'
  pod 'Nimble', '8.0.7'
end

reactNativeAbsolutePath = File.expand_path('../node_modules/react-native', __dir__)

# Set deployment target for all pods to get rid of (most of) warnings
post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end
    pi.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_NO_CONFIG=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_USE_LIBCPP=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_HAS_COROUTINES=0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DFOLLY_CFG_NO_COROUTINES=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_HAVE_CLOCK_GETTIME=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'NDEBUG=1'
      end
    end
    Dir.glob("Pods/RCT-Folly/folly/Portability.h").each do |file|
      text = File.read(file)
      new_contents = text.gsub('#define FOLLY_HAS_COROUTINES 1', '#define FOLLY_HAS_COROUTINES 0')
      File.open(file, "w") { |file| file.puts new_contents }
    end

   # fixes error: Signing for "React-Core-AccessibilityResources" requires a development team.
   # from https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1201464693
   pi.pods_project.targets.each do |target|
     if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
       target.build_configurations.each do |config|
         config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
       end
     end
   end
   # fix to override RN path in scripts
   pi.pods_project.targets.each do |target|
       target.shell_script_build_phases.each do |phase|
         if phase.name.include?('[RN]Check') || phase.name.include?('[CP-User] [Hermes] Replace Hermes')
           phase.shell_script = phase.shell_script.gsub('$REACT_NATIVE_PATH', reactNativeAbsolutePath)
           puts "[Podfile] REACT_NATIVE_PATH for '#{target.name}::#{phase.name}' has been overriden with #{reactNativeAbsolutePath}"
         end
       end
     end
end
